adobe/aem-core-email-components

content/src/content/jcr_root/apps/core/email/components/email-page/_cq_dialog/.content.xml

Added preheader to page dialog

---

content/package-lock.json
content/package.json
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/template-types/email-template-types/structure/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/email-template/structure/.content.xml
examples/ui.content/src/content/jcr_root/content/core-email-components-examples/.content.xml
testing/it/it-content/package-lock.json
testing/it/it-content/package.json
testing/it/ui-js/package-lock.json
testing/it/ui-js/package.json

Removed the arrow icons from the component menu as well as Layout mode

remove layout options

---

bundles/core/src/main/java/com/adobe/cq/email/core/components/servlets/package-info.java
content/src/content/jcr_root/apps/core/email/components/page/_cq_dialog/.content.xml

Fixed RTE personalization plugin in page properties

---

content/src/content/jcr_root/apps/core/email/components/page/page.html

Pull request that provides a fix for the two issues mentioned.

Fix for issue #65 and #69

---

content/src/content/jcr_root/apps/core/email/components/segmentation-item/segmentation-item.html

added context setting to condition #71

---

bundles/core/src/main/java/com/adobe/cq/email/core/components/models/SegmentationItemModel.java
content/src/content/jcr_root/apps/core/email/components/segmentation-item/_cq_dialog/.content.xml
content/src/content/jcr_root/apps/core/email/components/segmentation-item/segmentation-item.html

Features/issue #66

---

content/src/content/jcr_root/apps/core/email/components/page/head.html

Add context hub to the page component.

Fix RTE personalization in Text component #61

---

bundles/core/src/main/java/com/adobe/cq/email/core/components/models/SegmentationItemModel.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/models/SegmentationItemModelTest.java
content/src/content/jcr_root/apps/core/email/components/segmentation-item/segmentation-item.html

Updated logic for segmentation item component

---

content/src/content/jcr_root/apps/core/email/components/commons/xfpage/customheaderlibs.html
content/src/content/jcr_root/apps/core/email/components/experiencefragment/.content.xml
content/src/content/jcr_root/apps/core/email/components/title/_cq_dialog/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/policies/.content.xml

Added ContextHub to Experience Fragment Component

---

content/src/content/jcr_root/apps/core/email/components/title/title.html

Added title.html to Title Component

---

bundles/core/src/test/java/com/adobe/cq/email/core/components/internal/services/CoreEmailOpenCommandTest.java

Code coverage increase
Code coverage increase
https://github.com/adobe/aem-core-email-components/issues/107
jUnit code coverage improvement
jUnit tests

Code coverage increase

---

bundles/core/src/main/java/com/adobe/cq/email/core/components/configs/StylesInlinerConfig.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/constants/StylesInlinerConstants.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/exceptions/StylesInlinerException.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/filters/StylesInlinerFilter.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/internal/configuration/AuthorModeUIConfig.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/internal/css/CssInliner.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/internal/models/EmailPageImpl.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/internal/request/EmptyHttpServletRequest.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/internal/request/ResolverRequestWrapper.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/internal/services/CoreEmailAuthoringUIModeServiceImpl.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/internal/services/StylesInlinerServiceImpl.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/internal/services/UrlMapperServiceImpl.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/models/ContainerModel.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/models/EmailPage.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/models/ImageModel.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/models/SegmentationItemModel.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/pojo/StyleProperty.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/pojo/StyleSpecificity.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/pojo/StyleToken.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/pojo/package-info.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/services/StylesInlinerService.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/services/UrlMapperService.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/util/HtmlSanitizer.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/util/StyleExtractor.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/util/StyleMerger.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/util/StyleSpecificityFactory.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/util/StyleTokenFactory.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/util/StyleTokenizer.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/util/WrapperDivRemover.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/util/StyleTokenFactoryTest.java

JavaDoc addition
JavaDoc addition to all public methods, classes and constants
https://github.com/adobe/aem-core-email-components/issues/108
To increase code readability
No test needed: only JavaDoc addition

JavaDoc addition

---

content/src/content/jcr_root/apps/core/email/components/container/.content.xml
content/src/content/jcr_root/apps/core/email/components/container/_cq_dialog/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/policies/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/email-template/initial/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/email-template/structure/.content.xml
examples/ui.content/src/content/jcr_root/content/campaigns/core-email-components-examples/master/core-email-spender/e-mail-test-page/.content.xml
examples/ui.content/src/content/jcr_root/content/core-email-components-examples/core-email-components-examples/master/core-email-spender/e-mail-test-page/.content.xml

Update and Rename Container Component #90

---

bundles/core/src/main/java/com/adobe/cq/email/core/components/internal/services/AccLinkServiceImpl.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/internal/services/UrlMapperServiceImpl.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/models/ButtonModel.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/models/TitleModel.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/models/package-info.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/services/AccLinkService.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/services/package-info.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/internal/services/AccLinkServiceImplTest.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/models/ButtonModelTest.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/models/TitleModelTest.java
content/src/content/jcr_root/apps/core/email/components/button/_cq_dialog/.content.xml
content/src/content/jcr_root/apps/core/email/components/button/button.html
content/src/content/jcr_root/apps/core/email/components/button/clientlibs/.content.xml
content/src/content/jcr_root/apps/core/email/components/button/clientlibs/site/.content.xml
content/src/content/jcr_root/apps/core/email/components/button/clientlibs/site/css.txt
content/src/content/jcr_root/apps/core/email/components/button/clientlibs/site/css/button.css
content/src/content/jcr_root/apps/core/email/components/contentfragment/templates.html
content/src/content/jcr_root/apps/core/email/components/title/_cq_dialog/.content.xml
content/src/content/jcr_root/apps/core/email/components/title/clientlibs/.content.xml
content/src/content/jcr_root/apps/core/email/components/title/clientlibs/site/.content.xml
content/src/content/jcr_root/apps/core/email/components/title/clientlibs/site/css.txt
content/src/content/jcr_root/apps/core/email/components/title/clientlibs/site/css/title.css
content/src/content/jcr_root/apps/core/email/components/title/title.html

Features/update link title #104

---

bundles/core/src/main/java/com/adobe/cq/email/core/components/models/ButtonModel.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/models/TitleModel.java
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/email-template/initial/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/email-template/structure/.content.xml
examples/ui.content/src/content/jcr_root/content/campaigns/core-email-components-examples/master/core-email-spender/e-mail-test-page/.content.xml
examples/ui.content/src/content/jcr_root/content/core-email-components-examples/core-email-components-examples/master/core-email-spender/e-mail-test-page/.content.xml

Add missing versioning to components.

Create Component Versions #106

---

content/src/content/jcr_root/apps/core/email/components/title/v1/title/_cq_dialog/.content.xml
content/src/content/jcr_root/apps/core/email/components/title/v1/title/title.html

Title Component Fix #130

---

content/src/content/jcr_root/apps/core/email/components/container/v1/container/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/policies/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/email-template/policies/.content.xml

Add policies for each column of the container component.

Container component - column policy #125

---

content/package-lock.json
content/src/content/jcr_root/apps/core/email/components/image/v1/image/clientlibs/.content.xml
content/src/content/jcr_root/apps/core/email/components/image/v1/image/clientlibs/site/.content.xml
content/src/content/jcr_root/apps/core/email/components/image/v1/image/clientlibs/site/css.txt
content/src/content/jcr_root/apps/core/email/components/image/v1/image/clientlibs/site/css/image.css
content/src/content/jcr_root/apps/core/email/components/image/v1/image/image.html
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/action.html
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/actions.html
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/clientlibs/.content.xml
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/clientlibs/site/.content.xml
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/clientlibs/site/css.txt
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/clientlibs/site/css/teaser.css
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/description.html
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/image.html
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/pretitle.html
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/teaser.html
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/title.html
content/src/content/jcr_root/apps/core/email/components/text/v1/text/clientlibs/.content.xml
content/src/content/jcr_root/apps/core/email/components/text/v1/text/clientlibs/site/.content.xml
content/src/content/jcr_root/apps/core/email/components/text/v1/text/clientlibs/site/css.txt
content/src/content/jcr_root/apps/core/email/components/text/v1/text/clientlibs/site/css/text.css
content/src/content/jcr_root/apps/core/email/components/text/v1/text/text.html
examples/ui.apps/src/content/jcr_root/apps/core-email-components-examples/clientlibs/clientlib-base/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/policies/.content.xml

HTML markup updates
HTML markup update for Image, Teaser, Text and Title (Button is already defined without DIV tags)
https://github.com/adobe/aem-core-email-components/issues/23
DIV replace with table elements to enhance email client compatibility
Local AEM instance

HTML Markup updates

---

bundles/core/src/main/java/com/adobe/cq/email/core/components/models/ContainerColumn.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/models/ContainerModel.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/models/package-info.java
bundles/core/src/main/resources/conf/TestConf.json
bundles/core/src/test/java/com/adobe/cq/email/core/components/models/ContainerModelTest.java
bundles/core/src/test/resources/content/TestPage.json
content/src/content/jcr_root/apps/core/email/components/container/v1/container/_cq_template/.content.xml
content/src/content/jcr_root/apps/core/email/components/container/v1/container/container.html
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/policies/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/policies/_rep_policy.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/_rep_policy.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/email-template/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/email-template/_rep_policy.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/email-template/initial/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/email-template/policies/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/email-template/structure/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/experience-fragment/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/experience-fragment/initial/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/experience-fragment/policies/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/experience-fragment/structure/.content.xml
testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/AuthorBaseUITest.java
testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/button/ButtonIT.java
testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/container/ContainerIT.java
testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/experiencefragment/ExperienceFragmentIT.java
testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/image/ImageIT.java
testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/segmentation/SegmentationIT.java
testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/teaser/TeaserIT.java
testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/text/TextIT.java
testing/it/e2e-selenium/src/test/java/com/adobe/cq/wcm/core/components/it/seljup/tests/title/TitleIT.java

- extend container model to return container columns which can handle template resources
- update unit tests
- update example content
fixes #125

[Container] Enable policies for columns

---

examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/experience-fragment/initial/.content.xml

Update Experience Fragment Template to include acTemplateId

---

bundles/core/pom.xml
bundles/core/src/test/java/com/adobe/cq/email/core/components/exceptions/StylesInlinerExceptionTest.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/filters/InlinerResponseWrapperTest.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/internal/request/EmptyHttpServletRequestTest.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/internal/request/URITest.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/pojo/StyleTokenTest.java

Code coverage
Jacoco exclusions removal and code coverage improvements
https://github.com/adobe/aem-core-email-components/issues/107
Code coverage
Tested running jUnit tests via IDE and Maven task

Code coverage

---

examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/template-types/experience-fragment/structure/.content.xml
examples/ui.content/src/content/jcr_root/conf/core-email-components-examples/settings/wcm/templates/experience-fragment/structure/.content.xml
examples/ui.content/src/content/jcr_root/content/core-email-components-examples/.content.xml

Disable Layout Mode in Experience fragment page

---

content/src/content/jcr_root/apps/core/email/components/segmentation/v1/segmentation/item.html
content/src/content/jcr_root/apps/core/email/components/segmentation/v1/segmentation/segmentation.html

Fix for conditions rendered in preview mode 

---

content/.eslintrc
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/_cq_dialog/.content.xml
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/clientlibs/editor/.content.xml
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/clientlibs/editor/css.txt
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/clientlibs/editor/css/teaser.less
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/clientlibs/editor/js.txt
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js

- add JS to init ACMetadataPlugin after composite multifield got initialised
fixes #160

Teaser Component - Personalization Link does not work for CTA links

---

bundles/core/src/main/java/com/adobe/cq/email/core/components/models/TeaserModel.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/models/TeaserModelTest.java
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/actions.html
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/description.html
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/image.html
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/pretitle.html
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/teaser.html
content/src/content/jcr_root/apps/core/email/components/teaser/v1/teaser/title.html

- fix image template to place the img in a table proper cell
- include teaser sections conditionally
- add pre title to teaser model
#183 
Locally

fix: teaser markup (#183)

---

bundles/core/src/main/java/com/adobe/cq/email/core/components/internal/services/StylesInlinerServiceImpl.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/util/StyleTokenFactory.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/internal/services/StylesInlinerServiceImplTest.java
bundles/core/src/test/resources/testpage/unused_style.css
bundles/core/src/test/resources/testpage/unused_style_with_immediate_children.css

- add extra space between selector and properties
- adapt unit tests
fixes #193

Fix media queries for Outlook on ios

---

content/src/content/jcr_root/apps/core/email/components/commons/editor/dialog/segmenteditor/v1/segmenteditor/segmenteditor.html

- add missing dot to name prefix
fixes #209

Segmentation Component - Custom Conditions are stored under root (/)

---

content/src/content/jcr_root/apps/core/email/components/commons/editor/dialog/segmenteditor/v1/segmenteditor/clientlibs/css/segmenteditor.less
content/src/content/jcr_root/apps/core/email/components/commons/editor/dialog/segmenteditor/v1/segmenteditor/clientlibs/js/segmenteditor.js

- fix issue with insert component dialog for AEMaaCS

fix: make segment component AEMaaCS compatible

---

bundles/core/src/main/java/com/adobe/cq/email/core/components/util/StyleTokenizer.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/TestFileUtils.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/internal/services/StylesInlinerServiceImplTest.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/util/StyleTokenizerTest.java
bundles/core/src/test/resources/testpage/internal_css_with_inner_pseudo.html
bundles/core/src/test/resources/testpage/media_style_with_inner_pseudo.css
bundles/core/src/test/resources/testpage/other_style_with_inner_pseudo.css

fix: StyleTokenizer with inner pseudo selector

---

bundles/core/src/main/java/com/adobe/cq/email/core/components/internal/services/StylesInlinerServiceImpl.java
bundles/core/src/test/resources/testpage/internal_css_with_inner_pseudo.html

fix: SelectorParseException if media query is empty

---

content/src/content/jcr_root/apps/core/email/components/commons/editor/dialog/segmenteditor/v1/segmenteditor/segmenteditor.html

fix: Custom segments can't be renamend

---

bundles/core/src/main/java/com/adobe/cq/email/core/components/configs/StylesInlinerConfig.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/internal/services/StylesInlinerServiceImpl.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/util/StyleTokenFactory.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/util/StyleTokenizer.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/internal/services/StylesInlinerServiceImplTest.java
bundles/core/src/test/resources/testpage/internal_css_with_inner_pseudo.html
bundles/core/src/test/resources/testpage/other_style_with_inner_pseudo.css

fix: StyleInlinerException if nested rule contains separator

---

bundles/core/src/main/java/com/adobe/cq/email/core/components/internal/services/EmailLinkTransformerFactory.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/internal/services/EmailLinkTransformerFactoryTest.java

This extends the `EmailLinkTransformerFactory.TransformerImpl` to properly handle `img#srcset` and rewrite any image urls in there. See the unit tests for examples.
relates to #186

SITES-7750: transform img sources in srcset

---

bundles/core/pom.xml
examples/all/pom.xml
examples/ui.apps/pom.xml

fix: remove ui.config dependency in ui.apps content package

---

bundles/core/src/main/java/com/adobe/cq/email/core/components/internal/models/EmailPageImpl.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/models/EmailPage.java
bundles/core/src/main/java/com/adobe/cq/email/core/components/models/package-info.java
bundles/core/src/test/java/com/adobe/cq/email/core/components/internal/models/EmailPageImplTest.java
bundles/core/src/test/resources/editor/TestPage.json
content/src/content/jcr_root/apps/core/email/components/page/v1/page/page.html
testing/it/e2e-selenium/src/test/java/com/adobe/cq/email/core/components/it/seljup/tests/page/PageIT.java
testing/it/e2e-selenium/src/test/java/com/adobe/cq/email/core/components/it/seljup/util/components/page/EmailTab.java

- add sling model for email page and add getPreHeader method
- add div for pre header in page template
- add unit and selenium tests
fixes #250

Fix missing usage of the preheader page property

---

bundles/core/src/main/java/com/adobe/cq/email/core/components/internal/services/StylesInlinerServiceImpl.java
bundles/core/src/test/resources/testpage/internal_css_with_inner_pseudo.html
bundles/core/src/test/resources/testpage/other_style_with_inner_pseudo.css
testing/it/e2e-selenium/pom.xml
testing/it/it-content/package-lock.json
testing/it/it-content/package.json

- catch SelectorParseException and bypass usage check
fixes #262

SelectorParseException
